### PR TITLE
Add `nanocl version check` subcommand

### PR DESCRIPTION
**Pull request by zhiburt**
Hi there

This PR adds a new subcommand `nanocl version check`.
A command looks up GitHub in order to find a latest available version and outputs it.

I've considered #41 to be too strict, as the command would need to make assumptions about an installation process.
Like for example whether it was installed via `cargo install` etc.

So I think `cargo version check` a little bit more versatile and people can update themselves.

Take care

PS: Not sure whether it's better to print a message like `A NEW VERSION IS AVAILABLE; PLEASE UPDATE` instead of just a version number.

### CODE REVIEW

**Comment by leon3s** [comment]
Hey, your insane thank you for the PR!

I wanted to update the daemon by running this command because the daemon run inside a container.
But you'r right the CLI may not be compatible and he is harded to updated since he can have multiple installation way.
I'm not sure how to handle version compatibility yet so im gonna merge it and close the issue.

Could you had the test for your command ?
in `bin/nanocl/src/main.rs:38` :
```rust
  /// Test version command
  #[ntex::test]
  async fn test_version() {
    let args = Cli::parse_from(["nanocl", "version"]);
    assert!(execute_args(&args).await.is_ok());
    let args = Cli::parse_from(["nanocl", "version", "check"]);
    assert!(execute_args(&args).await.is_ok());
  }
```

Thank you for your time!

**Review by 0xle0ne — CHANGES_REQUESTED** [review]
Hey, your insane thank you for the PR!

I wanted to update the daemon by running this command because the daemon run inside a container.
But you'r right the CLI may not be compatible and he is harder to update since he can have multiple installation way.
I'm not sure how to handle version compatibility yet so im gonna merge it and close the issue.

Could you add the test for your command to not loose coverage, please ?
In `bin/nanocl/src/main.rs:38` :
```rust
  /// Test version command
  #[ntex::test]
  async fn test_version() {
    let args = Cli::parse_from(["nanocl", "version"]);
    assert!(execute_args(&args).await.is_ok());
    let args = Cli::parse_from(["nanocl", "version", "check"]);
    assert!(execute_args(&args).await.is_ok());
  }
```

Thank you for your time!

**Comment by zhiburt** [comment]
> I wanted to update the daemon by running this command because the daemon run inside a container.

You mean to update `nexthat/nanocl-get-started` image to latest and then restarting running container with latest if running?

**Review by 0xle0ne — APPROVED** [review]

**Comment by 0xle0ne** [comment]
The daemon is `nanocld`, its image is not released on DockerHub -  it's the tarball we download during the `nanocl setup` command.
I should actually release it on DockerHub but the project will soon have release v0.2.0 -> i'm waiting for @scirin to finish the proxy controller. That is why the documentation at the moment can be a bit outdated.
The name of the image used is `nanocl-daemon` and we should  update it by downloading his new image and running a `nanocl cargo patch` command. The daemon his itself registered as a cargo that way we can update it and scale like any other container.

**Pull request merged**
